# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "9.0.7" %}
{% set zulu_build = "9.0.7.1" %}
{% set build_number = 0 %}
{% set sha256_linux = "45f2dfbee93b91b1468cf81d843fc6d9a47fef1f831c0b7ceff4f1eb6e6851c8" %}
{% set sha256_osx = "4b1f8529ff3a8bebc974e2a22395cb27ad8750e386c8c4d1b0a1b16f89cfcf66" %}
{% set sha256_win = "75f76c53c6a1f12b1a571b86bd9708ab75adf582d689dddc94fdd77dcc0f3f5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip    # [osx]
  url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip       # [win64]
  sha256: {{ sha256_linux }}  # [linux64]
  sha256: {{ sha256_osx }}    # [osx]
  sha256: {{ sha256_win }}    # [win64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: zulu{{ zulu_build }}_{{ build_number }}
  track_features:
    - openjdk

requirements:
  build:
    - curl

test:
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh                                # [not win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://www.azul.com/products/zulu/
  license: GPLv2
  summary: The Zulu OpenJDK build.
  description: |
    Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
