{% set name = "openjdk" %}
{% set version = "8.0.144" %}
{% set zulu_build = "8.23.0.3" %}
{% set build_number = 1001 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
    sha256: 7e6284739c0e5b7142bc7a9adc61ced70dc5bb26b130b582b18e809013bcb251  # [linux64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-macosx_x64.zip  # [osx]
    sha256: ff533364c9cbd3b271ab5328efe28e2dd6d7bae5b630098a5683f742ecf0709d  # [osx]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-jdk{{ version }}-win_x64.zip  # [win64]
    sha256: f1d9d3341ef7c8c9baff3597953e99a6a7c64f8608ee62c03fdd7574b7655c02  # [win64]

  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux64]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux64]
    folder: fonts  # [linux64]

build:
  number: {{ build_number }}
  skip: true  # [win32 or linux32]
  string: zulu{{ zulu_build }}_{{ build_number }}

requirements:
  host:
    - {{ compiler('c') }}

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]

about:
  home: https://www.azul.com/products/zulu/
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: The Zulu OpenJDK build.
  description: Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
